services:
  - type: web
    name: kompetans-site
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn kompetans2.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: kompetans2.settings
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
    staticPublishPath: staticfiles
