# Generated by Django 5.2.4 on 2025-07-03 16:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_formation', models.CharField(choices=[('habilitation', 'Habilitations électriques'), ('nfc15100', 'Formation à la NF C15-100'), ('formateur', 'Formation de formateur en habilitation électrique'), ('cse', 'Formation des élus du Comité social et économique (CSE)')], max_length=50)),
                ('description_courte', models.TextField()),
                ('description_longue', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='formations/')),
                ('duree', models.CharField(blank=True, max_length=100)),
                ('prix', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
            },
        ),
        migrations.CreateModel(
            name='ContactFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('entreprise', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('traite', models.BooleanField(default=False)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.formation')),
            ],
            options={
                'verbose_name': 'Demande de contact',
                'verbose_name_plural': 'Demandes de contact',
                'ordering': ['-date_creation'],
            },
        ),
    ]
