# Generated by Django 5.2.4 on 2025-08-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_formation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='prix_numerique',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
