name: Keep Render Site Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # toutes les 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render site
        run: |
          curl -sSf https://kompetans.fr || echo "Ping failed"
